server:
  port: 8888
spring:
  application:
    name: config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cheonwooo/Spring-Cloud-Cofing-test
          search-paths: config-file/**
          default-label: main