server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cheonwooo/Spring-Cloud-Cofing-test
          search-paths: config-file/**
          default-label: main